name: Build y Empaquetado Electron

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependencias
        run: npm install

      - name: Construir la aplicación React (carpeta dist)
        run: npm run build

      - name: Empaquetar con Electron (genera dist_electron)
        run: npm run dist

      - name: Subir artefacto de la aplicación empaquetada
        uses: actions/upload-artifact@v3
        with:
          name: dist_electron
          path: dist_electron/
